### ISSUE TITLE
Hàm getTransactionsHistory

### ISSUE THREAD

**Issue by 12520349** [CookieGMVN/MBBank#17]
Hiện nay tạo tài khoản bằng số đt, request truy vấn lịch sử giao dịch nó post dạng `{"accountNo":"1xxxxxxxxxx4","fromDate":"12/07/2024","toDate":"19/07/2024"...}, thay vì accountName. Bạn fix giúp nhé :) tks

**Comment by CookieGMVN** [comment]
@12520349 Mình sẽ thêm vào phiên bản tiếp theo nhé, cảm ơn bạn!

**Comment by thedtvn** [comment]
> @12520349 Mình sẽ thêm vào phiên bản tiếp theo nhé, cảm ơn bạn!

:))) bảo từ lúc add rồi :)))

**Comment by CookieGMVN** [comment]
Mặc định library đã sử dụng `accountNo` khi request lên MB và chỉ sử dụng parameter `accountNumber` để tường minh hơn trong việc code.

**Comment by thuanqt** [comment]
getTransactionsHistory thì bị lỗi như bên dưới bác à

```
MBBank# node test.js
undefined:1
field accountNo is not set
 ^

SyntaxError: Unexpected token 'i', "field accou"... is not valid JSON
    at JSON.parse (<anonymous>)


```

**Comment by CookieGMVN** [comment]
@thuanqt Thay vì copy-paste example một cách máy móc như vậy (example này đã rất cũ và không còn chính xác) thì bạn vào [docs](https://mb-bank.vercel.app/classes/MB.default.html#getTransactionsHistory) tìm hiểu cách dùng hàm giúp mình.
