### ISSUE TITLE
lưu session trong database

### ISSUE THREAD

**Issue by phapntm** [CookieGMVN/MBBank#2]
có thể cho phép người dùng lấy session ròi lưu trong database để đỡ phải login nhiều lần không?
thấy nó đặt private mất rồi

**Comment by CookieGMVN** [comment]
@phapntm Có thể nhưng session id sẽ bị MB đánh invalid liên tục (tầm 15p là hết session rồi) + không có endpoint để renew session, nên kiểu gì cũng phải login lại thôi bạn.
