### ISSUE TITLE
load dataenc lỗi trả về chuỗi rỗng

### ISSUE THREAD

**Issue by T3DCode** [CookieGMVN/MBBank#27]
Hình như bên gốc đổi cách mã hóa hay sao mà dataenc trả về rỗng

**Comment by CookieGMVN** [comment]
@T3DCode Hi bạn, hiện mình mới test lại thì thấy library vẫn hoạt động bình thường, và MB vẫn chưa đổi cách mã hóa. Mình nghĩ rằng bạn đang sử dụng phiên bản cũ của library. Bạn vui lòng kiểm tra lại:
- File `package.json` đã hiện là `mbbank: ^1.5.3` chưa, nếu chưa bạn hãy chạy lệnh `npm i mbbank@1.5.3` để cập nhật.
- Nếu bạn chỉ sử dụng hàm dataEnc của library, bạn vui lòng kiểm tra giúp mình file `src/utils/LoadWasm.ts` đã ở phiên bản mới nhất chưa.

**Comment by T3DCode** [comment]
<img width="589" alt="Screenshot 2024-10-05 at 16 05 42" src="https://github.com/user-attachments/assets/4ee3be18-06a0-4f62-9cad-e8368c5b618d">
Mình chạy thì vẫn báo lỗi
đã update code rồi anh ơi

**Comment by CookieGMVN** [comment]
@T3DCode Hi bạn, bạn có thể chụp cho mình toàn bộ lỗi được xuất ra ở console không nhỉ?

**Comment by T3DCode** [comment]
<img width="733" alt="image" src="https://github.com/user-attachments/assets/0e2de081-526a-4071-b50e-9c17fdc66a89">
Nó báo vầy nè anh

**Comment by CookieGMVN** [comment]
@T3DCode Bạn có thể chụp dòng bạn sử dụng hàm dataEnc được không nhỉ?

**Comment by T3DCode** [comment]
này e dùng console log chỗ hàm login thư viện của anh. 
<img width="908" alt="image" src="https://github.com/user-attachments/assets/7d213477-9475-4a10-a74e-3542a9949b55">
Em thấy login lỗi nên log ra thử nó trống thật

**Comment by thedtvn** [comment]
> này e dùng console log chỗ hàm login thư viện của anh. <img alt="image" width="908" src="https://private-user-images.githubusercontent.com/174975005/373860841-7d213477-9475-4a10-a74e-3542a9949b55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjAzNTIsIm5iZiI6MTcyODEyMDA1MiwicGF0aCI6Ii8xNzQ5NzUwMDUvMzczODYwODQxLTdkMjEzNDc3LTk0NzUtNGExMC1hNzRlLTM1NDJhOTk0OWI1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwOTIwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTIyZGI0YmE5NTIxMTM1NDc4YjRkZTFiZjNkMDBlZmU0OWIxOWZjYzAxYWU5OGVmYjBmODRlZDFjZTFlM2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R2JRhF1TWS_WJgHk1aAPrP5vIBCNcGNvmgSjs48y5Vs"> Em thấy login lỗi nên log ra thử nó trống thật

@T3DCode bạn  send cái req  data  được  ko
![image](https://github.com/user-attachments/assets/bdced695-25e0-44da-b20e-285f4d539a70)
cái  này nè

**Comment by thedtvn** [comment]
*  xóa  pass +  user  giúp  mình

**Comment by CookieGMVN** [comment]
Issue sẽ bị đóng vì lỗi ở phía người dùng. Library đã được kiểm tra là vẫn hoạt động bình thường.

**Comment by T3DCode** [comment]
e clone code moi nhat ve van loi tuong tư
e dung chay test nhu code anh
<img width="869" alt="image" src="https://github.com/user-attachments/assets/5e3d21c0-99f3-4a66-a91b-bd4dbaf53f7c">

**Comment by CookieGMVN** [comment]
Như mình đã nói, vấn đề sẽ nằm ở phía bạn. Mình vừa mới chạy thử và nó vẫn cho ra kết quả:
![image](https://github.com/user-attachments/assets/873bfa4d-62d3-4dea-9cec-e25e6dbd3bca)

**Comment by aiko-chan-ai** [comment]
.-.

**Comment by T3DCode** [comment]
Cảm ơn anh đã trả lời. Đúng là thu viện LoadWasm cua e bị cũ
