### ISSUE TITLE
OCR captcha drop ~ 70%

### ISSUE THREAD

**Issue by lacvietanh** [CookieGMVN/MBBank#3]
Cảm ơn chủ thớt về một công trình tuyệt vời, mình đang tìm cách xử lý captcha MB Bank và thấy repo này, mừng rỡ đi thử đoạn code nhận diện khoảng vài chục captcha mbbank thì thấy chưa có cái nào chính xác, thay psm từ 1 tới 13 vẫn trả về đa phần là kết quả rỗng. 
Mấu chốt vướng mắc nhất của các cách thức truy cập api mbbank đều khó ở captcha. 
Kết nối với dịch vụ bên 2captcha thì tỉ lệ chính xác cũng khá cao nhưng chờ khoảng vài phút

**Comment by CookieGMVN** [comment]
Xin chào bạn @lacvietanh, nếu bạn đã thử đoạn code nhận diện thì bạn đã dùng luôn phần lọc đường kẻ captcha (captchaImagePRCLine1, captchaImagePRCLine2) chưa? Nếu chưa thì tesseract sẽ rất khó để nhận diện được kí tự trên captcha. Riêng với thư viện này, mình đã test và độ chính xác nó sẽ nằm tầm 70% (chạy thử 10 cái thì nó nhận 7 cái).

**Comment by lacvietanh** [comment]
uây thiếu sót của mình🥺 mình ko biết có chỗ đó.. đúng là nếu lọc đường kẻ noise đi thì package này nhận diện chữ chuẩn lắm luôn.. mà mình gà mờ chưa đọc được hết code chưa rõ vụ khử đường kẻ chỗ nào.. để mình xem lại..

Tuần qua mình đã tích hợp api của bên sieuthicode.. cũng người VN mà không rõ họ dùng công nghệ nào để xử lý captcha, mình đọc log gần 500 cái chưa trật phát nào🥶

**Comment by CookieGMVN** [comment]
@lacvietanh Hi bạn, bạn kiểm tra từ line 46 -> line 74 src/MB.ts nhé!
