### ISSUE TITLE
issues after 1.3.0 update 

### ISSUE THREAD

**Issue by alta1212** [CookieGMVN/MBBank#6]
Hello, thank you very much for fixing my API issue today. However, after updating the code, I would like to contribute a few suggestions:

In your documentation, the parameter passed is mentioned as accountName, but in the node module, it appears as accountNumber.
In the historyData.transactionHistoryList section, you might want to check if it's null before executing the foreach loop.
Everything else is working well, and I appreciate that.

**Comment by CookieGMVN** [comment]
@alta1212 Uh oh, some typing issues here. By the way, for the next version, I will improve the code and validation rules. Thank you!
