### ISSUE TITLE
Phản hồi chậm

### ISSUE THREAD

**Issue by kb-0912** [CookieGMVN/MBBank#9]
Cảm ơn code của bạn, mình đang test thử nhưng mỗi request lấy lịch sử giao dịch đều tốn khoảng 2-3 phút mới có phản hồi. Không biết nguyên nhân do đâu bạn nhỉ

**Comment by CookieGMVN** [comment]
@kb-0912 Chào bạn, về vấn đề bạn vừa nêu, bạn vui lòng kiểm tra các vấn đề sau:
- Không đăng nhập MB Web trên bất kỳ nơi nào khác ngoài library, vì sẽ gây đăng nhập lại.
- Chỉ sử dụng duy nhất 1 instance MB, và khuyến khích nên giữ lại instance MB đó trong suốt quá trình chạy để lấy lịch sử giao dịch, vì nếu tạo mới thì sẽ cần đăng nhập lại => giải captcha lại => gây chậm cho toàn bộ tiến trình.

Nếu bạn đã làm hết những cách trên mà library vẫn còn chậm, bạn có thể trả lời ở đây để mình tiến hành benchmark và fix lại nhé!

**Comment by kb-0912** [comment]
Cảm ơn phản hồi của bạn, hiện mình không đăng nhập MB Web tại bất kì nơi nào khác. Ngoài ra mình chỉ sử dụng 1 instance MB như bạn nói. 
Kết quả phản hồi là ngẫu nhiên, giao động từ 1p - 3p

**Comment by CookieGMVN** [comment]
@kb-0912 Chào bạn, mình đã tiến hành benchmark 20 test lấy lịch sử giao dịch và cho ra kết quả dưới đây. Bạn có thể xem qua:
![image](https://github.com/CookieGMVN/MBBank/assets/73780382/69313a1a-4f1e-4020-9464-3cbd783fabfe)
Như trên, bạn có thể thấy test chậm nhất chỉ lấy dữ liệu và phản hồi trong vòng 196ms, toàn bộ test xét trung bình chỉ 99.25ms nên việc giao động từ 1-3p như bạn nói là khó xảy ra.

Bạn vui lòng kiểm tra lại đường truyền Internet, giảm khoảng thời gian tra soát giao dịch (có thể là từ 1-3 ngày). Nếu có bất kỳ vấn đề gì bạn có thể hỏi mình ngay tại đây. Nếu vấn đề đã được giải quyết, bạn vui lòng đóng issue giúp mình. Cảm ơn bạn!

**Comment by kb-0912** [comment]
Bạn có thể cho mình xin phương thức liên lạc để mình gửi code của mình và review giúp mình được không? Tele hoặc Discord đều dc ạ

**Comment by CookieGMVN** [comment]
@kb-0912 Chào bạn, bạn có thể liên hệ với mình qua Discord: `@cookiegmvn` nhé!

**Comment by kb-0912** [comment]
Mình đã gửi yêu cầu kết bạn trên discord, với có addd bạn trong repo mà mình đang cần trọ giup
